#!/usr/bin/env python

# https://data.lacity.org/A-Prosperous-City/Listing-of-Active-Businesses/6rrh-rzua

import os
import sys
import csv
import json
import re
import requests
import logging

if __name__ == "__main__":

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-P', '--postcodes', dest='postcodes', action='store', default=None, help='... (Default is None')
    opt_parser.add_option('-A', '--api-key', dest='api_key', action='store', default=None, help='... (Default is None)')

    opt_parser.add_option('-O', '--outfile', dest='outfile', action='store', default=None, help="... (Default is STDOUT)")

    opt_parser.add_option('-s', '--strict', dest='strict', action='store_true', default=False, help='... (Default is False)')
    opt_parser.add_option('-d', '--debug', dest='debug', action='store_true', default=False, help='... (Default is False)')
    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is False)')

    options, args = opt_parser.parse_args()

    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    #

    has_pypostal = False

    try:
        from postal.parser import parse_address
        has_pypostal = True

        logging.info("libpostal is installed, using local bindings for address parsing")

    except Exception, e:

        if not options.api_key:
            logging.error("libpostal is not installed, so a valid Mapzen API key is required")
            sys.exit(1)

    #

    # sudo put me in a function...

    postalcodes = {}

    if options.postcodes:

        pc = open(options.postcodes, "r")
        reader = csv.reader(pc)
        
        for row in reader:
            name, lat, lon = row
            name = name.replace(" ", "")
            
            lat = float(lat)
            lon = float(lon)
            
            postalcodes[ name  ] = [ lat, lon ]

    #

    source_prefix = "lacity_oof"
    source_key = "id"

    #

    if options.outfile:
        out = open(options.outfile, "w")
    else:
        out = sys.stdout

    #

    pat = re.compile(r'\((\-?\d+\.\d+),\s*(\-?\d+\.\d+)\)')

    for path in args:

        fh = open(path, "r")
        
        reader = csv.DictReader(fh)
        
        for row in reader:
            
            id = row["LOCATION ACCOUNT #"]
            name = row["BUSINESS NAME"]

            addr = row["STREET ADDRESS"]
            city = row["CITY"]
            zipcode = row["ZIP CODE"]
            loc = row["LOCATION"]
                            
            is_approx = False
            lat = None
            lon = None
            
            if loc != "":

                m = pat.match(loc)

                if m:
                    gr = m.groups()
                    lat = float(gr[0])
                    lon = float(gr[1])

            if lat == None or lon == None:

                if options.postcodes:
                    
                    zipcode = zipcode.split("-")
                    zipcode = zipcode[0]

                    coords = postalcodes.get(zipcode, None)

                    if coords:
                        lat, lon = coords
                        is_approx = True

            if lat == None or lon == None:
                logging.warning("can't sort out coordinates for %s (in %s), skipping" % (id, zipcode))
                continue

            #

            address = " ".join((addr, city, zipcode))

            house_number = None
            street = None

            try:

                if has_pypostal:

                    rsp = parse_address(address)
                    lookup = {}
                    
                    for pair in rsp:
                        v, k = pair

                        possible = lookup.get(k, [])
                        possible.append(v)                        
                        lookup[k] = possible
                        
                    house_number = lookup.get("house_number", None)
                    street = lookup.get("road", None)

                    if house_number:
                        house_number = house_number[0]

                    if street:
                        street = street[0]
                
                else:
                
                    url = "https://libpostal.mapzen.com/parse"
                    params = { "address" : address, "format": "keys", "api_key": api_key }
                    
                    rsp = requests.get(url, params=params)
                    rsp = json.loads(rsp.content)
                    
                    house_number = rsp["house_number"][0]
                    street = rsp["road"][0]
                    
            except Exception, e:

                    logging.error("failed to parse address (%s) because %s" % (address, e))

                    if options.strict:
                        sys.exit(1)

                    continue

            #

            lat = float(lat)
            lon = float(lon)

            coords = [ lon, lat ]
            geom = { "type": "Point", "coordinates": coords }

            source_id = "%s:%s=%s" % (source_prefix, source_key, id)

            props = {
                "name": name,
                "addr:housenumber": house_number,
                "addr:street": street,
                "addr:full": address,
            }

            if is_approx:
                props["mz:is_approximate"] = 1

            feature = {
                "type": "Feature",
                "geometry": geom,
                "properties": props,
                "id": source_id
            }
            
            out.write(json.dumps(feature))
            out.write("\n")

        sys.exit(0)
