#!/usr/bin/env python

raise Exception, "please write me..."

import sys
import mapzen.whosonfirst.lieu.utils

if __name__ == "__main__":

    iter = mapzen.whosonfirst.lieu.utils.crawl(sys.argv[1:])
    idx.index_documents_bulk(iter)
