#!/usr/bin/env python

#!/usr/bin/env python

import os
import sys
import json
import pprint

if __name__ == "__main__":

    fh = sys.stdout

    for path in sys.argv[1:]:

        fh = open(path, "r")

        for ln in fh:

            data = json.loads(ln)

            if not data["is_dupe"]:
                continue

            sys.stdout.write(ln)               