#!/usr/bin/env python
# -*-python-*-

import os
import sys
import json
import logging

if __name__ == "__main__":

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('-O', '--outfile', dest='outfile', action='store', default=None, help="... (Default is STDOUT)")
    opt_parser.add_option('-N', '--no-dupes', dest='no_dupes', action='store_true', default=False, help="... (Default is False)")

    opt_parser.add_option('-d', '--debug', dest='debug', action='store_true', default=False, help='... (Default is False)')
    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is False)')

    options, args = opt_parser.parse_args()

    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    #

    if options.outfile:
        out = open(options.outfile, "w")
    else:
        out = sys.stdout

    for path in args:

        fh = open(path, "r")

        for ln in fh:

            data = json.loads(ln)

            is_dupe = data["is_dupe"]

            if is_dupe and options.no_dupes:
                logging.debug("is dupe but skipping dupes")
                continue
            elif not is_dupe and not options.no_dupes:
                logging.debug("is not dupe but require dupes")
                continue
            else:
                pass

            out.write(ln)               
