#!/usr/bin/env python

import sys
import mapzen.whosonfirst.lieu.utils
import mapzen.whosonfirst.lieu.search

if __name__ == "__main__":

    idx = mapzen.whosonfirst.lieu.search.index()

    crawl = mapzen.whosonfirst.lieu.utils.crawl(sys.argv[1:])

    for report in crawl:

        iter = idx.prepare_report_bulk(report)

        for r in iter:
            print r

        # break

        # idx.index_documents_bulk(iter)
